<div class="jumbotron">
    <h4 ><span>Pesquisa de Sala de aula: </span></h4>
    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="button">Pesquisar</button>
      </span>
        <input type="text" class="form-control" placeholder="Informe o nome da sala de aula">
    </div>
    <hr>
    <a class="btn btn-success" href="#" target="_self">Adicionar &raquo;</a>

</div>
<div >
    <table class="table table-bordered table-condensed table-hover">
        <thead>
        <tr class="btn-primary">
            <th>#</th>
            <th>Sala de aula</th>
            <th>Inscrição</th>
            <th>Fim inscrição</th>
            <th>Status</th>
            <td>Ação</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th>1</th>
            <td>Sala 1</td>
            <td>01/07/2016</td>
            <td>10/12/2017</td>
            <td>Ativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        <tr>
            <th>101</th>
            <td>Sala 2</td>
            <td>01/01/2017</td>
            <td>01/01/2018</td>
            <td>Inativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>

        </tbody>
    </table>
</div>