<div class="jumbotron">
    <h1><span class="zf-green">Página Venda</span></h1>

    <p>

        A prática cotidiana prova que a competitividade nas transações comerciais nos obriga à análise dos paradigmas
        corporativos. No mundo atual, a consolidação das estruturas promove a alavancagem do levantamento das
        variáveis envolvidas. Gostaria de enfatizar que a contínua expansão de nossa atividade representa uma
        abertura para a melhoria das direções preferenciais no sentido do progresso.
        building your application on ZF.
    </p>

    <p><a class="btn btn-success btn-lg" href="#" target="_blank">Alterar &raquo;</a></p>
</div>
