<div class="jumbotron">
    <h4 ><span>Pesquisar Matrículas: </span></h4>
    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="button">Pesquisar</button>
      </span>
        <input type="text" class="form-control" placeholder="Informe o nome do aluno">
    </div>
    <hr>
    <a class="btn btn-success" href="#" target="_self">Adicionar &raquo;</a>

</div>
<div >
    <table class="table table-bordered table-condensed table-hover">
        <thead>
        <tr class="btn-primary">
            <th>ID Venda</th>
            <th>Nome do aluno</th>
            <th>Matrícula</th>
            <th>Status</th>
            <td>Ação</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th>100</th>
            <td>Reinaldo Farias</td>
            <td>100201</td>
            <td>Ativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        <tr>
            <th>101</th>
            <td>Fred Mercury</td>
            <td>100202</td>
            <td>Ativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        <tr>
            <th>102</th>
            <td>Rubens adamastor</td>
            <td>100203</td>
            <td>Ativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        <tr>
            <th>103</th>
            <td>Homem biscoito</td>
            <td>100204</td>
            <td>Ativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        </tbody>
    </table>
</div>