<div class="jumbotron">
    <h1><span class="zf-green">Página Usuario </span></h1>
    <h1><span >Utilizando Branche usuario </span></h1>
    <p>

        Caros amigos, a execução dos pontos do programa pode nos levar a considerar a reestruturação das regras
        de conduta normativas. O que temos que ter sempre em mente é que a percepção das dificuldades faz parte de
        um processo de gerenciamento das diretrizes de desenvolvimento para o futuro. O cuidado em identificar pontos
        críticos na consulta aos diversos militantes talvez venha a ressaltar a relatividade do sistema de participação geral.
        No entanto, não podemos esquecer que a necessidade de renovação processual aponta para a melhoria do fluxo de informações.

    </p>

    <p><a class="btn btn-success btn-lg" href="#" target="_blank">Cadastrar &raquo;</a></p>
</div>
