<div class="jumbotron">
    <h4 ><span>Pesquisa de Usuários: </span></h4>
    <a class="btn btn-success" href="#" target="_self">Adicionar &raquo;</a>
</div>
<div class="jumbotron">
    <table class="table table-bordered table-condensed table-hover">
        <thead>
        <tr class="btn-primary">
            <th>#</th>
            <th>Nome</th>
            <th>Telefone</th>
            <th>Status</th>
            <td>Ação</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th>1</th>
            <td>Reinaldo Farias</td>
            <td>61 9832 7587</td>
            <td>Ativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        <tr>
            <th>101</th>
            <td>Robson Pereira</td>
            <td>61 9932 8587</td>
            <td>Inativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        <tr>
            <th>1</th>
            <td>Reinaldo Farias</td>
            <td>61 9832 7587</td>
            <td>Ativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        <tr>
            <th>101</th>
            <td>Robson Pereira</td>
            <td>61 9932 8587</td>
            <td>Inativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        </tbody>
    </table>
</div>
