<div class="jumbotron">
    <h1><span class="zf-green">Página LMS</span></h1>

    <p>
        Desta maneira, a hegemonia do ambiente político auxilia a preparação e a composição das condições inegavelmente
        apropriadas. Acima de tudo, é fundamental ressaltar que o consenso sobre a necessidade de qualificação oferece
        uma interessante oportunidade para verificação dos índices pretendidos. O incentivo ao avanço tecnológico, assim
        como o aumento do diálogo entre os diferentes setores produtivos acarreta um processo de reformulação e
        modernização das condições financeiras e administrativas exigidas.

    </p>

    <p><a class="btn btn-success btn-lg" href="#" target="_blank">Deletar &raquo;</a></p>
</div>
