<div class="jumbotron">
    <h1><span class="zf-green">Página Disciplina</span></h1>

    <p>

        Nunca é demais lembrar o peso e o significado destes problemas, uma vez que o novo modelo estrutural aqui
        preconizado garante a contribuição de um grupo importante na determinação das novas proposições. Pensando mais a
        longo prazo, a constante divulgação das informações prepara-nos para enfrentar situações atípicas decorrentes dos
        conhecimentos estratégicos para atingir a excelência. Do mesmo modo, o entendimento das metas propostas facilita
        a criação do sistema de formação de quadros que corresponde às necessidades.
    </p>

    <p><a class="btn btn-success btn-lg" href="#" target="_blank">Editar &raquo;</a></p>
</div>
