<div class="jumbotron">
    <h1><span class="zf-green">Página LMS</span></h1>

    <p>

        Por outro lado, o desafiador cenário globalizado exige a precisão e a definição dos métodos utilizados na
        avaliação de resultados. É importante questionar o quanto a complexidade dos estudos efetuados não pode mais
        se dissociar de todos os recursos funcionais envolvidos. Não obstante, o início da atividade geral de formação
        de atitudes assume importantes posições no estabelecimento dos níveis de motivação departamental. A certificação
        de metodologias que nos auxiliam a lidar com o fenômeno da Internet cumpre um papel essencial na formulação do
        processo de comunicação como um todo.
    </p>

    <p><a class="btn btn-success btn-lg" href="/user/editar" target="_self">Fork Zend Framework on GitHub &raquo;</a></p>
</div>


