<div class="jumbotron">
    <h4 ><span>Pesquisa de Produtos: </span></h4>
    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="button">Pesquisar</button>
      </span>
        <input type="text" class="form-control" placeholder="Informe o nome do produto">
    </div>
    <hr>
    <a class="btn btn-success" href="#" target="_self">Adicionar &raquo;</a>

</div>
<div >
    <table class="table table-bordered table-condensed table-hover">
        <thead>
        <tr class="btn-primary">
            <th>#</th>
            <th>Produto</th>
            <th>Projeto</th>
            <th>Status</th>
            <td>Ação</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th>1</th>
            <td>Produto 1</td>
            <td>Projeto 5</td>
            <td>Ativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        <tr>
            <th>101</th>
            <td>Produto 2</td>
            <td>Projeto 3</td>
            <td>Inativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        <tr>
            <th>1</th>
            <td>Produto 3</td>
            <td>Projeto 1</td>
            <td>Ativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        <tr>
            <th>101</th>
            <td>Produto 4</td>
            <td>Projeto 2</td>
            <td>Inativo</td>
            <td><a class="btn btn-info" href="#" target="_self">Editar &raquo;</a></td>
        </tr>
        </tbody>
    </table>
</div>
