<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title zf-green">Matrículas</h3>
            </div>
            <div class="panel-body">
                <p>
                    O cuidado em identificar pontos críticos no comprometimento entre as equipes aponta para a melhoria
                    do sistema de formação de quadros que corresponde às necessidades. Ainda assim, existem dúvidas a
                    respeito de como a adoção de políticas descentralizadoras faz parte de um processo de gerenciamento
                    das direções preferenciais no sentido do progresso. Assim mesmo, a determinação clara de objetivos
                    possibilita uma melhor visão global das novas proposições.
                </p>

                <p><a class="btn btn-success pull-right" href="#" target="_blank">Acão 1 &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title zf-green">Alocar Aluno</h3>
            </div>
            <div class="panel-body">
                <p>
                    O incentivo ao avanço tecnológico, assim como o desenvolvimento contínuo de distintas formas de
                    atuação exige a precisão e a definição do levantamento das variáveis envolvidas. Neste sentido, o
                    desafiador cenário globalizado cumpre um papel essencial na formulação das regras de conduta normativas.
                    É claro que a complexidade dos estudos efetuados facilita a criação do orçamento setorial. Não obstante,
                    o entendimento das metas propostas ainda não demonstrou convincentemente que vai participar na mudança
                    do retorno esperado a longo prazo.
                </p>

                <p><a class="btn btn-success pull-right" href="#" target="_blank">Ação 2 &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title zf-green">Solicitação de documentos</h3>
            </div>
            <div class="panel-body">
                <p>
                    Acima de tudo, é fundamental ressaltar que o aumento do diálogo entre os diferentes setores produtivos
                    afeta positivamente a correta previsão do sistema de participação geral. A nível organizacional, o
                    consenso sobre a necessidade de qualificação pode nos levar a considerar a reestruturação das diretrizes
                    de desenvolvimento para o futuro. Por outro lado, a percepção das dificuldades agrega valor ao
                    estabelecimento da gestão inovadora da qual fazemos parte. Todavia, a expansão dos mercados mundiais
                    promove a alavancagem das diversas correntes de pensamento.
                </p>

                <p><a class="btn btn-success pull-right" href="#" target="_blank">Ação 3 &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
