<div class="jumbotron">
    <h1><span class="zf-green">Página Usuario</span></h1>

    <table class="table table-bordered table-default table-hover">
        <thead>
            <tr align="center" class="bg-primary">
                <th >#</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>Telefone</th>
                <th>email</th>
                <th class="hidden">login</th>
                <th class="hidden">Password</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            <tr align="center">
                <td>1</td>
                <td>Conteúdo cabeçalho 1</td>
                <td>Conteúdo cabeçalho 1</td>
                <td>Conteúdo cabeçalho 1</td>
                <td>Conteúdo cabeçalho 1</td>
                <td class="hidden">Conteúdo cabeçalho 1</td>
                <td class="hidden">Conteúdo cabeçalho 1</td>
                <td >
                    <a href="#" class="btn btn-info btn-sm" ><i class="glyphicon glyphicon-edit"></i></a>
                    <a href="#" class="btn btn-danger btn-sm" ><i class="glyphicon glyphicon-remove"></i></a>

                </td>
            </tr>
            <tr align="center">
                <td>2</td>
                <td>Conteúdo cabeçalho 1</td>
                <td>Conteúdo cabeçalho 1</td>
                <td>Conteúdo cabeçalho 1</td>
                <td>Conteúdo cabeçalho 1</td>
                <td class="hidden">Conteúdo cabeçalho 1</td>
                <td class="hidden">Conteúdo cabeçalho 1</td>
                <td >
                    <a href="#" class="btn btn-info btn-sm" ><i class="glyphicon glyphicon-edit"></i></a>
                    <a href="#" class="btn btn-danger btn-sm" ><i class="glyphicon glyphicon-remove"></i></a>

                </td>
            </tr>
        </tbody>
    </table>

    <p><a class="btn btn-success btn-lg" href="/user/editar" target="_self">Fork Zend Framework on GitHub &raquo;</a></p>
</>


